# Generated by Django 2.2.2 on 2019-10-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="url",
            field=models.URLField(verbose_name="Site URL"),
        )
    ]
