# Generated by Django 2.2.2 on 2019-10-15 03:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_auto_20191014_0254"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="site", unique_together={("user", "url", "category")}
        )
    ]
